version: 1.0.{build}
image: Visual Studio 2015
configuration:
- Debug
- Release
environment:
  matrix:
  - CMAKE_GEN_TYPE: '"Visual Studio 9 2008"'
    ADDITIONAL_INCLUDE_PATH: C:\Libraries\boost
  - CMAKE_GEN_TYPE: '"Visual Studio 10 2010"'
    ADDITIONAL_INCLUDE_PATH: C:\Libraries\boost
  - CMAKE_GEN_TYPE: '"Visual Studio 11 2012"'
    ADDITIONAL_INCLUDE_PATH: C:\Libraries\boost
  - CMAKE_GEN_TYPE: '"Visual Studio 12 2013"'
  - CMAKE_GEN_TYPE: '"Visual Studio 14 2015"'
  - CMAKE_GEN_TYPE: '"Visual Studio 14 2015 Win64"'
install:
- ps: >-
    if(!(Test-Path -Path lua-5.3.3 )){
      choco install 7zip.commandline
      Invoke-WebRequest  http://www.lua.org/ftp/lua-5.3.3.tar.gz -OutFile lua-5.3.3.tar.gz
      7z x lua-5.3.3.tar.gz
      7z x lua-5.3.3.tar
    }
cache:
- lua-5.3.3
build_script:
- ps: >-
    if(!(Test-Path -Path build )){
      mkdir build
    }

    cd build

    cmake ../ -G $env:CMAKE_GEN_TYPE -DADDITIONAL_INCLUDE_PATH="$env:ADDITIONAL_INCLUDE_PATH" -DLOCAL_LUA_DIRECTORY="lua-5.3.3"

    cmake --build . --config $env:CONFIGURATION
test_script:
- ps: ctest -C $env:CONFIGURATION --output-on-failure
